import Head from 'next/head'
import { Inter } from '@next/font/google'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Sidebar from '@/components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
      <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white2 flex flex-row'>
        <div className='w-[264px] h-[895px] ml-[0px] mt-[0px]'>
          <Sidebar/>
        </div>

        <div className='flex flex-col'>
          <div className='w-[1415px] h-[83px] mt-[0px]'>
            <Navbar/>
          </div>

          <div className='w-[1415px] h-[813px]'>
            Main frame
          </div>
        </div>
      </main>
    </>
  )
}
